### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by sargeow** [sisby-folk/portable-crafting-standalone#17] opened 2024-09-26 04:30 UTC
[crash-2024-09-26_00.25.42-client.txt](https://github.com/user-attachments/files/17142725/crash-2024-09-26_00.25.42-client.txt)
Thanks

**Comment by sleepingdragoninn** [comment] 2024-09-26 08:50
dupe of #15, incompatibility with visual workbench.

**Closed as not planned by sleepingdragoninn** 2024-09-26 08:50 UTC
